{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.mahmudindev.mcmod.orenoconfig",
    "module": "orenoconfig-common",
    "version": "0.0.4+1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "orenoconfig-common-0.0.4+1.20.1.jar",
          "url": "orenoconfig-common-0.0.4+1.20.1.jar",
          "size": 85797,
          "sha512": "fb25b5cd9787a4b899c50bb6cc947557976f02952f3eda3303e6f8521f8d80b4668921d6db5ae8760aa498d1621a09c62c7ed18179e8c74a8c329a1127c93543",
          "sha256": "c814f748815e72e10c597d82e31bab7569de35197f447f5e27a440cbd23647d1",
          "sha1": "adf0be328ef8d635435b7c0ff4599a7c720bcb1f",
          "md5": "5e99a1e98f080dfe9d130d5504cb7bc5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.14"
          }
        },
        {
          "group": "com.github.mahmudindev.mcmod.orenocommons",
          "module": "orenocommons-common",
          "version": {
            "requires": "0.0.9+1.20.1"
          }
        },
        {
          "group": "com.github.mahmudindev.mcmod.orenoevents",
          "module": "orenoevents-common",
          "version": {
            "requires": "0.0.4+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "orenoconfig-common-0.0.4+1.20.1.jar",
          "url": "orenoconfig-common-0.0.4+1.20.1.jar",
          "size": 85797,
          "sha512": "fb25b5cd9787a4b899c50bb6cc947557976f02952f3eda3303e6f8521f8d80b4668921d6db5ae8760aa498d1621a09c62c7ed18179e8c74a8c329a1127c93543",
          "sha256": "c814f748815e72e10c597d82e31bab7569de35197f447f5e27a440cbd23647d1",
          "sha1": "adf0be328ef8d635435b7c0ff4599a7c720bcb1f",
          "md5": "5e99a1e98f080dfe9d130d5504cb7bc5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "orenoconfig-common-0.0.4+1.20.1-sources.jar",
          "url": "orenoconfig-common-0.0.4+1.20.1-sources.jar",
          "size": 27186,
          "sha512": "856b819e26ffc4776ed1fdb7ae7c2794cd0a25f43d050607e40a736be13a46bb346888ed0e99354f40ff558d1a8dfba1a9f061ba0aa909f45aaa54dbf11ad8c5",
          "sha256": "e635fbbad1d9fc66d3661d842239b59f14ce237593ee03e92254a326116ee0d4",
          "sha1": "b58a679e8d49bd79554fd145c9a68f31aebca615",
          "md5": "1e38be75818f9d30d71a2be961032f22"
        }
      ]
    }
  ]
}
